In [1]:
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)

[1 2 3 4]
1
(4,)


In [2]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [3]:
A = np.array([[1, 2], [3, 4]] )
print(A.shape)
B = np.array([[5, 6], [7, 8]])
print(B.shape)
np.dot(A, B)

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
print(A)

B = np.array(([[1, 2], [3, 4], [5, 6]] ) )
print(B.shape)
print(B)

np.dot(A, B)

(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])

In [5]:
X = np.array([1, 2])
print(X)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
Y = np.dot(X, W)
print(Y)

[1 2]
[[1 3 5]
 [2 4 6]]
[ 5 11 17]
